---
- name: Run disk_usage.sh script on remote host
  hosts: all
  become: true

  tasks:
    - name: Copy disk_usage.sh to remote host
      copy:
        src: /home/anil/shell/disk_usage.sh
        dest: /tmp/disk_usage.sh

    - name: Make disk_usage.sh executable
      file:
        path: /tmp/disk_usage.sh
        mode: 'u+x'

    - name: Run disk_usage.sh script and capture output
      shell: /tmp/disk_usage.sh
      register: disk_usage_output

    - name: Display script output
      debug:
        var: disk_usage_output.stdout_lines

